In [2]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("../data/processed/final_enriched_rental_data.csv")
data["hour"] = pd.to_datetime(data["hour"])
data["date"] = pd.to_datetime(data["date"])

In [6]:
hourly_data = (
    data.groupby("hour", as_index=False)
    .agg(
        total_count=("total_count", "sum"),
        registered_count=("registered_count", "sum"),
        direct_count=("direct_count", "sum"),
        # zero_demand_locations=("is_zero_filled_rental", "sum"),
        hour_of_day=("hour_of_day", "first"),
        day_of_week=("day_of_week", "first"),
        month=("month", "first"),
        # quarter=("quarter", "first"),
        is_weekend=("is_weekend", "first"),
        is_workday=("is_workday", "first"),
        is_holiday=("is_holiday", "first"),
        conditions=("conditions", "first"),
        temperature_c=("temperature_c", "first"),
        perceived_temperature_c=("perceived_temperature_c", "first"),
        humidity=("humidity", "first"),
        windspeed_kmh=("windspeed_kmh", "first"),
        is_missing_weather=("is_missing_weather", "first"),
    )
)

hourly_data.head()

,hour,total_count,registered_count,direct_count,hour_of_day,day_of_week,month,is_weekend,is_workday,is_holiday,conditions,temperature_c,perceived_temperature_c,humidity,windspeed_kmh,is_missing_weather
0,2011-01-01 00:00:00,16,13,3,0,5,1,1,0,0,clear,3.3,3.0,81.0,0.0,0
1,2011-01-01 01:00:00,40,32,8,1,5,1,1,0,0,clear,2.3,2.0,80.0,0.0,0
2,2011-01-01 02:00:00,32,27,5,2,5,1,1,0,0,clear,2.3,2.0,80.0,0.0,0
3,2011-01-01 03:00:00,13,10,3,3,5,1,1,0,0,clear,3.3,3.0,75.0,0.0,0
4,2011-01-01 04:00:00,1,1,0,4,5,1,1,0,0,clear,3.3,3.0,75.0,0.0,0

In [8]:
hourly_target_summary = pd.DataFrame({
    "location_hour_target": data["total_count"].describe(),
    "hourly_target": hourly_data["total_count"].describe(),
})

hourly_target_summary

       location_hour_target  hourly_target
count         368424.000000   17544.000000
mean               8.937200     187.681202
std                9.121555     181.456478
min                0.000000       0.000000
25%                2.000000      38.000000
50%                6.000000     140.000000
75%               13.000000     279.000000
max               64.000000     977.000000