In [3]:
import pandas as pd

data = pd.read_csv("../dg_pipeline/processed/final_model_data.csv")
data.head()

,hour,location_id,direct_count,registered_count,total_count,is_missing_rental,date,hour_of_day,day_of_week,month,is_weekend,conditions,temperature_c,perceived_temperature_c,humidity,windspeed_kmh,is_missing_weather,is_holiday
0,2011-01-01 00:00:00,0,0,0,0,1,2011-01-01,0,5,1,1,clear,3.3,3.0,81.0,0.0,0,0
1,2011-01-01 00:00:00,1,0,0,0,1,2011-01-01,0,5,1,1,clear,3.3,3.0,81.0,0.0,0,0
2,2011-01-01 00:00:00,2,1,0,1,0,2011-01-01,0,5,1,1,clear,3.3,3.0,81.0,0.0,0,0
3,2011-01-01 00:00:00,3,0,1,1,0,2011-01-01,0,5,1,1,clear,3.3,3.0,81.0,0.0,0,0
4,2011-01-01 00:00:00,4,0,2,2,0,2011-01-01,0,5,1,1,clear,3.3,3.0,81.0,0.0,0,0

In [11]:
data["hour"] = pd.to_datetime(data["hour"])

data["quarter"] = data["hour"].dt.quarter
data["month"] = data["hour"].dt.month

In [4]:
data.columns

Index(['hour', 'location_id', 'direct_count', 'registered_count',
       'total_count', 'is_missing_rental', 'date', 'hour_of_day',
       'day_of_week', 'month', 'is_weekend', 'conditions', 'temperature_c',
       'perceived_temperature_c', 'humidity', 'windspeed_kmh',
       'is_missing_weather', 'is_holiday'],
      dtype='str')

In [5]:
data.describe()

,location_id,direct_count,registered_count,total_count,is_missing_rental,hour_of_day,day_of_week,month,is_weekend,temperature_c,perceived_temperature_c,humidity,windspeed_kmh,is_missing_weather,is_holiday
count,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000,368424.000000
mean,10.000000,1.682890,7.254310,8.937200,0.152102,11.500000,3.002736,6.519836,0.287278,15.262896,15.281122,62.842767,12.794374,0.009405,0.028728
std,6.055309,2.662112,7.674525,9.121555,0.359120,6.922196,2.003418,3.449556,0.452493,9.079545,11.385721,19.303595,8.234173,0.096522,0.167041
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,-7.100000,-16.000000,0.000000,0.000000,0.000000,0.000000
25%,5.000000,0.000000,1.000000,2.000000,0.000000,5.750000,1.000000,4.000000,0.000000,8.000000,6.000000,48.000000,7.000000,0.000000,0.000000
50%,10.000000,1.000000,5.000000,6.000000,0.000000,11.500000,3.000000,7.000000,0.000000,15.500000,16.000000,63.000000,13.000000,0.000000,0.000000
75%,15.000000,2.000000,11.000000,13.000000,0.000000,17.250000,5.000000,10.000000,1.000000,23.000000,25.000000,79.000000,17.000000,0.000000,0.000000
max,20.000000,28.000000,59.000000,64.000000,1.000000,23.000000,6.000000,12.000000,1.000000,39.000000,50.000000,100.000000,57.000000,1.000000,1.000000

In [10]:
data["is_missing_rental"].value_counts()
data.groupby("is_missing_rental")["total_count"].agg(["count", "mean", "min", "max"])

                    count       mean  min  max
is_missing_rental
0                  312386  10.540418    1   64
1                   56038   0.000000    0    0

Rows with `is_missing_rental = 1` were added when creating a complete hourly-location grid. Their rental counts were filled with 0, which means that these rows represent hours where no rental event was recorded.

In [6]:
data["total_count"].value_counts()

total_count
0     56038
1     33751
2     24199
3     20437
4     18663
      ...
58        6
62        5
61        3
59        2
64        1
Name: count, Length: 64, dtype: int64

In [ ]:
FEATURES = ["hour", "location_id", "date", "hour_of_day", "day_of_week", "mont", "is_weekend", "conditions",]